-- SQLite

-- Consultas avançadas

SELECT  L.ID AS 'Código da locação',
        L.TOTAL AS 'Valor da locação',
        C.NAME AS 'Cliente',
        E.NAME AS 'Funcionário',
        CARS.NAME AS 'Veículo'
FROM LOCATIONS AS L
JOIN EMPLOYEES AS E ON L.EMPLOYEE_ID = E.ID
JOIN CARS ON L.CAR_ID = CARS.ID
JOIN CUSTOMERS AS C ON L.CUSTOMER_ID = C.ID;

SELECT COUNT(ID) AS 'Quantidade de locações' 
FROM LOCATIONS;

SELECT * FROM LOCATIONS 
WHERE TOTAL = (SELECT MAX(TOTAL) FROM LOCATIONS);

SELECT * FROM LOCATIONS
WHERE START_DATE BETWEEN '2022-05-20' AND '2022-12-25';