-- SQLite

-- Primeiras consultas

SELECT NAME, LASTNAME, EMAIL FROM CUSTOMERS
WHERE STATE = 'SP';

SELECT * FROM CARS WHERE STATUS = 'Liberado';

SELECT * FROM CARS WHERE YEAR = 2016;

SELECT  E.NAME AS 'Funcionário', 
        P.DESCRIPTION AS 'Cargo'
FROM EMPLOYEES AS E
JOIN POSITIONS AS P ON E.POSITION_ID = P.ID;

SELECT E.NAME AS 'Funcionário'
FROM EMPLOYEES AS E
LEFT JOIN LOCATIONS AS L ON L.EMPLOYEE_ID = E.ID
GROUP BY E.ID
HAVING COUNT(L.ID) >= 2;

SELECT C.NAME AS 'Cliente'
FROM CUSTOMERS AS C
LEFT JOIN LOCATIONS AS L ON L.CUSTOMER_ID = C.ID
GROUP BY C.ID
HAVING COUNT(L.ID) >= 2;